# This is a basic workflow to help you get started with Actions

name: CI

# on: [push, pull_request]
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: likesalmon/github-actions-sandbox@v1.0.1
