# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
