# This is a basic workflow to help you get started with Actions

name: Output

on: [push, pull_request, workflow_dispatch]

jobs:
  set-output:
    runs-on: ubuntu-latest
    steps:
      - name: Set output variable
        run: echo "::set-output name=THE_DATE::$(date +%s)"
        id: SetOutput
      - run: echo "The output is ${{steps.SetOutput.outputs.THE_DATE}}"
